apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        version: {{ .Chart.Version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: {{ .Release.Name }}-config-volume
              mountPath: /data/www/index.html
              subPath: index.html
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
